spring:
  application:
    name: api-gateway

server:
  port: 8801

eureka:
  instance:
    instance-id: zuul-inst001
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    service-a:
      path: /api/**
    service-b:
      path: /api/**
